## Saving

In [9]:
import tensorflow as tf

In [2]:
tf.reset_default_graph()
# Create some variables.
v1 = tf.get_variable("v1", shape=[5], initializer = tf.zeros_initializer)
v2 = tf.get_variable("v2", shape=[5], initializer = tf.zeros_initializer)

**Remember**

>1) Tensors that should be retrieved must be added to collection

>2) Varibales are automatically added

In [3]:
inc_v1 = v1.assign(v1+1)
dec_v2 = v2.assign(v2-1)
w = v1+v2
tf.add_to_collection("output",w) #Since this is not a variable, this should be added

# Add an op to initialize the variables.
init_op = tf.global_variables_initializer()

In [4]:
sess = tf.InteractiveSession()
sess.run(init_op)
print(sess.run(w))

[0. 0. 0. 0. 0.]


### Saving checkpoint and graph

In [5]:
# Add ops to save and restore all the variables.
saver = tf.train.Saver()
saver.save(sess,"logs/model.chpt")
tf.summary.FileWriter("logs/event/",sess.graph)

In [6]:
# import the inspect_checkpoint library
from tensorflow.python.tools import inspect_checkpoint as chkp

### Inspecting checkpoint

In [7]:
chkp.print_tensors_in_checkpoint_file("logs/model.chpt",tensor_name='', all_tensors=True,all_tensor_names=True)

tensor_name:  v1
[0. 0. 0. 0. 0.]
tensor_name:  v2
[0. 0. 0. 0. 0.]


In [8]:
chkp.print_tensors_in_checkpoint_file("logs/model.chpt",tensor_name='v1', all_tensors=False,all_tensor_names=False)

tensor_name:  v1
[0. 0. 0. 0. 0.]


In [11]:
sess.close()