## Broadcasting

Rules for operating arrays of different dimensions

In [45]:
import tensorflow as tf
import numpy as np


**Remember**

>1) When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (right-most) dimensions, and works its way forward. Two dimensions are compatible when

>>1) They are equal, or

>>2) One of them is 1

**Example :**

    A      (2d array):  5 x 4
    B      (1d array):      4
    Result (2d array):  5 x 4

    A      (2d array):  5 x 4
    B      (1d array):      1
    Result (2d array):  5 x 4

    A      (1d array):      4
    B      (1d array):      5
    Result MISMATCH  :  WRONG

    A      (2d array):  4 x 1
    B      (1d array):      5
    Result (2d array):  4 x 5

    A      (4d array):  8 x 1 x 6 x 1
    B      (3d array):      7 x 1 x 5
    Result (4d array):  8 x 7 x 6 x 5

    Image  (3d array): 256 x 256 x 3
    Scale  (1d array):             3
    Result (3d array): 256 x 256 x 3



#### Illustration 1:

    A      (2d array):  10 x 4
    B      (1d array):      4
    Result (2d array):  10 x 4


In [63]:
a= np.tile(np.arange(0,40,10),(10,1))
c = tf.convert_to_tensor(a,dtype=tf.int32)
d = tf.constant([1,2,3,4],dtype=tf.int32)
r = d+c
print(a, "\n+\n", [1,2,3,4],"\n=\n",tf.Session().run(r))

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]] 
+
 [1, 2, 3, 4] 
=
 [[ 1 12 23 34]
 [ 1 12 23 34]
 [ 1 12 23 34]
 [ 1 12 23 34]
 [ 1 12 23 34]
 [ 1 12 23 34]
 [ 1 12 23 34]
 [ 1 12 23 34]
 [ 1 12 23 34]
 [ 1 12 23 34]]


**Illustration 2:**

    A      (2d array):  5 x 1
    B      (1d array):      2
    Result (2d array):  5 x 2
    
0  <span style="color:orange">0</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5 6<br>
1  <span style="color:orange">1</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:orange">5</span> <span style="color:orange">6</span><br> 
2  <span style="color:orange">2</span>&nbsp;&nbsp;&nbsp; **+**&nbsp;&nbsp;&nbsp;<span style="color:orange">5</span> <span style="color:orange">6</span><br>
3  <span style="color:orange">3</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:orange">5</span> <span style="color:orange">6</span><br>
4  <span style="color:orange">4</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:orange">5</span> <span style="color:orange">6</span><br>

In [70]:
a= tf.range(0,5)
b = tf.range(5,7)

c = b+ tf.expand_dims(a, axis=1) 
print(np.arange(0,5), "\n+\n", np.arange(5,7),"\n=\n",tf.Session().run(c))

[0 1 2 3 4] 
+
 [5 6] 
=
 [[ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]]


**Remember**
>2) Broadcasting rules work for *, - and / operations as well