## Linear Algebra

In [22]:
import tensorflow as tf
import numpy as np
np.set_printoptions(suppress=True) ## Supress printing in scientific notations
np.set_printoptions(precision=2)

### 1) SVD

#### Arbitrary square matix


In [59]:
a = np.arange(0,25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
c = tf.convert_to_tensor(a,dtype=tf.float64)
s,u,v = tf.svd(c,full_matrices=True) ##if full_matrices is FALSE (default), redundunt singular values and vectors are dropped
print("s = ", tf.Session().run(s), "\n")
print("U = ", tf.Session().run(u), "\n")
print("V = ", tf.Session().run(v), "\n")

m = tf.matmul(tf.matmul(u,tf.diag(s)),tf.transpose(v))
print("U.D(s).V^T =", tf.Session().run(m))

s =  [69.91  3.58  0.    0.    0.  ] 

U =  [[ 0.07  0.77  0.    0.63  0.02]
 [ 0.23  0.5  -0.36 -0.61 -0.44]
 [ 0.39  0.23  0.16 -0.35  0.81]
 [ 0.55 -0.05  0.74  0.01 -0.39]
 [ 0.7  -0.32 -0.55  0.32 -0.  ]] 

V =  [[ 0.39 -0.67 -0.14  0.6  -0.13]
 [ 0.42 -0.35 -0.25 -0.77 -0.21]
 [ 0.45 -0.04  0.32 -0.08  0.83]
 [ 0.47  0.28  0.67  0.05 -0.5 ]
 [ 0.5   0.59 -0.6   0.19  0.01]] 

U.D(s).V^T = [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


#### Symmetric matrix

Note that U=V

For a regular matrix $C$, the symmetric matrices can be formed as $CC^{T}$ and $C^{T}C$ (Positive Semi-Definite).

Eigen values are real and non-negative and Eigen vectors are L.I

In [61]:
sc = tf.matmul(c,tf.transpose(c))
tf.Session().run(sc)

array([[  30.,   80.,  130.,  180.,  230.],
       [  80.,  255.,  430.,  605.,  780.],
       [ 130.,  430.,  730., 1030., 1330.],
       [ 180.,  605., 1030., 1455., 1880.],
       [ 230.,  780., 1330., 1880., 2430.]])

In [62]:
s,u,v = tf.svd(sc)
print("s = ", tf.Session().run(s), "\n")
print("U = ", tf.Session().run(u), "\n")
print("V = ", tf.Session().run(v), "\n")

m = tf.matmul(tf.matmul(u,tf.diag(s)),tf.transpose(v))
print("U.D(s).V^T =", tf.Session().run(m))

s =  [4887.21   12.79    0.      0.      0.  ] 

U =  [[ 0.07  0.77  0.32  0.48 -0.27]
 [ 0.23  0.5  -0.   -0.43  0.72]
 [ 0.39  0.23 -0.32 -0.56 -0.62]
 [ 0.55 -0.05 -0.63  0.52  0.18]
 [ 0.7  -0.32  0.63 -0.   -0.  ]] 

V =  [[ 0.07  0.77  0.32 -0.48 -0.27]
 [ 0.23  0.5  -0.    0.43  0.72]
 [ 0.39  0.23 -0.32  0.56 -0.62]
 [ 0.55 -0.05 -0.63 -0.52  0.18]
 [ 0.7  -0.32  0.63  0.   -0.  ]] 

U.D(s).V^T = [[  30.   80.  130.  180.  230.]
 [  80.  255.  430.  605.  780.]
 [ 130.  430.  730. 1030. 1330.]
 [ 180.  605. 1030. 1455. 1880.]
 [ 230.  780. 1330. 1880. 2430.]]


#### Rectangular matrix

For $C \in \mathbb{R}^{M \times N}$,

$U \in \mathbb{R}^{M \times M}$

$V \in \mathbb{R}^{N \times N}$

$s \in \mathbb{R}^{P} \qquad P = min(M,N) $

In [63]:
a = np.arange(0,20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [65]:
c = tf.convert_to_tensor(a,dtype=tf.float64)
s,u,v = tf.svd(c,full_matrices=True)
print("s = ", tf.Session().run(s), "\n")
print("U = ", tf.Session().run(u), "\n")
print("V = ", tf.Session().run(v), "\n")

s =  [49.63  2.55  0.    0.  ] 

U =  [[ 0.06 -0.77  0.56 -0.22  0.18]
 [ 0.22 -0.5  -0.65  0.41  0.33]
 [ 0.39 -0.23 -0.34 -0.49 -0.66]
 [ 0.55  0.05  0.38  0.65 -0.38]
 [ 0.71  0.32  0.05 -0.34  0.53]] 

V =  [[ 0.44  0.71 -0.27 -0.48]
 [ 0.48  0.27  0.    0.84]
 [ 0.52 -0.18  0.8  -0.24]
 [ 0.56 -0.62 -0.53 -0.12]] 



**To reconstruct matrices**, we need to construct a rectangular diagonal matrix. Instead, just set **full_matrices = False**. Now U and V becomes partial matrices such that $UDV^{T}$ can be computed

In [66]:
c = tf.convert_to_tensor(a,dtype=tf.float64)
s,u,v = tf.svd(c)
print("s = ", tf.Session().run(s), "\n")
print("U = ", tf.Session().run(u), "\n")
print("V = ", tf.Session().run(v), "\n")

m = tf.matmul(tf.matmul(u,tf.diag(s)),tf.transpose(v))
print("U.D(s).V^T =", tf.Session().run(m))

s =  [49.63  2.55  0.    0.  ] 

U =  [[ 0.06 -0.77  0.56 -0.22]
 [ 0.22 -0.5  -0.65  0.41]
 [ 0.39 -0.23 -0.34 -0.49]
 [ 0.55  0.05  0.38  0.65]
 [ 0.71  0.32  0.05 -0.34]] 

V =  [[ 0.44  0.71 -0.27 -0.48]
 [ 0.48  0.27  0.    0.84]
 [ 0.52 -0.18  0.8  -0.24]
 [ 0.56 -0.62 -0.53 -0.12]] 

U.D(s).V^T = [[-0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]


### 2) Diagonal matrices and parting diagonal elements

In [48]:
i = tf.range(1,6,dtype=tf.float32)*tf.eye(5,dtype=tf.float32)
print(tf.Session().run(i))
d = tf.diag_part(i)
print(tf.Session().run(d))

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]
[1. 2. 3. 4. 5.]


### 3) Matrix norm

**Frobenius norm or 2-norm or euclidean norm**

$||A||_{2} = (\sum_{i}\sum_{j}a_{ij}^{2})^{1/2}$

In [91]:
a = tf.ones((5,5),dtype=tf.float32)
print(tf.Session().run(a))
norm_2 = tf.norm(a)
tf.Session().run(norm_2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


5.0

**1 Matrix norm**

Maximum of column sums

In [102]:
a = tf.convert_to_tensor(np.arange(0,20).reshape(5,4), dtype=tf.float32)
print(tf.Session().run(a))
norm_1 = tf.reduce_max(tf.norm(a,ord=1,axis=0))
print(tf.Session().run(norm_1))
print( "Which is max of ...", tf.Session().run(tf.norm(a,ord=1,axis=0)))

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
55.0
Which is max of ... [40. 45. 50. 55.]


In [93]:
3+7+11+15+19

55

**Infinite Matrix norm**

Maximum of row sums

In [101]:
a = tf.convert_to_tensor(np.arange(0,20).reshape(5,4), dtype=tf.float32)
print(tf.Session().run(a))
norm_1 = tf.reduce_max(tf.norm(a,ord=1,axis=1))
print(tf.Session().run(norm_1))
print( "Which is max of ...", tf.Session().run(tf.norm(a,ord=1,axis=1)))

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
70.0
Which is max of ... [ 6. 22. 38. 54. 70.]


In [89]:
16+17+18+19

70

### 4) Vector norm

**Remember :**
>1) tf.norm considers even matrices as vectors

** 1 vector norm**

Sum of all elements

$||A||_{1} = (\sum_{i}\sum_{j}a_{ij}^{1})^{1}$

In [96]:
a = tf.convert_to_tensor(np.arange(0,20).reshape(5,4), dtype=tf.float32)
print(tf.Session().run(a))
norm_1 = tf.norm(a,ord=1)
tf.Session().run(norm_1)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]


190.0

** Infinite vector norm**

Maximum of all elements

$||A||_{\inf} = max(a_{ij})$

In [95]:
a = tf.convert_to_tensor(np.arange(0,20).reshape(5,4), dtype=tf.float32)
print(tf.Session().run(a))
norm_inf = tf.norm(a,ord=np.Inf)
tf.Session().run(norm_inf)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]


19.0

### 5) Tensor Dot Contraction

Multiples each element of one tensor to every element of other tensor. (i.e)

> $C_{ijlm} = A_{ij}B_{lm}$

> Order(4) = Order(2)*Order(2)

To reduce along an axis, specify the two indices in **axis** argument. Length of those axes should be equal.

>$C_{im} = \sum_{k}A_{ik}B_{km} \qquad axes = [1,0]$

> Order(2) = Order(2)*Order(2) - 2

In [113]:
a = tf.ones((3,2),dtype=tf.float32)
b = 2*tf.ones((2,4),dtype=tf.float32)

c_tdot = tf.tensordot(a,b,axes=[[1],[0]]) ## Equivalent to matrix multiplication
c_matmul = tf.matmul(a,b)
tf.Session().run((c_tdot,c_matmul))

(array([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]], dtype=float32), array([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]], dtype=float32))

**Remember :**
>2) **tf.tensordor** should be used for **higher-order** tensor contractions

In [119]:
a = tf.ones((3,2,3),dtype=tf.float32)
b = 2*tf.ones((4,2,4),dtype=tf.float32)
c_tdot = tf.tensordot(a,b,axes=[[1],[1]])
print("Shape A :", a.shape)
print("Shape B :", b.shape)
print("Axes : [1,1]")
print("Resulting shape :", tf.Session().run(c_tdot).shape)

Shape A : (3, 2, 3)
Shape B : (4, 2, 4)
Axes : [1,1]
Resulting shape : (3, 3, 4, 4)
