## Reduction

In [7]:
import tensorflow as tf
import numpy as np

In [41]:
a = np.tile(np.arange(0,4),(5,1))
print(a)
print(a.shape)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
(5, 4)


### A) Reduce Sum

<u>**Reduction with numpy**</u>

**1) Sum all elements**

In [18]:
print(np.sum(a).shape)
print(np.sum(a))

()
30


**2) Sum each column**

Axis 0 is reduced

In [9]:
print(np.sum(a,axis=0).shape)
print(np.sum(a,axis=0))

(4,)
[ 0  5 10 15]


**3) Sum each row**

Axis 1 is reduced

In [10]:
print(np.sum(a,axis=1).shape)
print(np.sum(a,axis=1))

(5,)
[6 6 6 6 6]


<u>**Reduction with tf**</u>

In [19]:
c = tf.convert_to_tensor(a)
r = tf.reduce_sum(c)
print(r.shape)
tf.Session().run(r)

()


30

In [16]:
c = tf.convert_to_tensor(a)
r = tf.reduce_sum(c,axis=0)
print(r.shape)
tf.Session().run(r)

(4,)


array([ 0,  5, 10, 15])

In [15]:
c = tf.convert_to_tensor(a)
r = tf.reduce_sum(c,axis=1)
print(r.shape)
tf.Session().run(r)

(5,)


array([6, 6, 6, 6, 6])

**Keepdims**

Does not change the array dimension. The reduced dimension changes to 1.

In [14]:
c = tf.convert_to_tensor(a)
r = tf.reduce_sum(c,axis=0,keepdims=True)
print(r.shape)
tf.Session().run(r)

(1, 4)


array([[ 0,  5, 10, 15]])

In [17]:
c = tf.convert_to_tensor(a)
r = tf.reduce_sum(c,axis=1,keepdims=True)
print(r.shape)
tf.Session().run(r)

(5, 1)


array([[6],
       [6],
       [6],
       [6],
       [6]])

### B) Reduce Product

<u>**Reduction with numpy**</u>

In [22]:
print("All :", np.product(a))
print("Cols :", np.product(a,axis=0))
print("Rows :", np.product(a,axis=1))

All : 0
Cols : [  0   1  32 243]
Rows : [0 0 0 0 0]


<u>**Reduction with tf**</u>

In [27]:
c = tf.convert_to_tensor(a)
r1 = tf.reduce_prod(c)
r2 = tf.reduce_prod(c,axis=0)
r3 = tf.reduce_prod(c,axis=1)

with tf.Session() as sess:
    n1,n2,n3 = sess.run((r1,r2,r3))
    
print("All :", n1)
print("Cols :", n2)
print("Rows :", n3)

All : 0
Cols : [  0   1  32 243]
Rows : [0 0 0 0 0]


### C) Reduce_all

Computes the "**logical and**" of **boolean tensor**

In [62]:
print(a)
ab = (a==1) + (a==3)
c = tf.convert_to_tensor(ab)
tf.Session().run(c)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [64]:
r1 = tf.reduce_all(c)
r2 = tf.reduce_all(c,axis=0)
r3 = tf.reduce_all(c,axis=1)

with tf.Session() as sess:
    n1,n2,n3 = sess.run((r1,r2,r3))
    
print("All :", n1)
print("Cols :", n2)
print("Rows :", n3)

All : False
Cols : [False  True False  True]
Rows : [False False False False False]


### D) Reduce_any

Computes the "**logical or**" of **boolean tensor**

In [65]:
r1 = tf.reduce_any(c)
r2 = tf.reduce_any(c,axis=0)
r3 = tf.reduce_any(c,axis=1)

with tf.Session() as sess:
    n1,n2,n3 = sess.run((r1,r2,r3))
    
print("All :", n1)
print("Cols :", n2)
print("Rows :", n3)

All : True
Cols : [False  True False  True]
Rows : [ True  True  True  True  True]


### E) Reduce_join

For concatinating strings

In [66]:
a =  tf.constant([["a", "b"], ["c", "d"]])

tf.reduce_join(a, 0) #==> ["ac", "bd"]
tf.reduce_join(a, 1) #==> ["ab", "cd"]
tf.reduce_join(a, -2) #= tf.reduce_join(a, 0) ==> ["ac", "bd"]
tf.reduce_join(a, -1) #= tf.reduce_join(a, 1) ==> ["ab", "cd"]
tf.reduce_join(a, 0, keep_dims=True) #==> [["ac", "bd"]]
tf.reduce_join(a, 1, keep_dims=True) #==> [["ab"], ["cd"]]
tf.reduce_join(a, 0, separator=".") #==> ["a.c", "b.d"]
tf.reduce_join(a, [0, 1]) #==> ["acbd"]
tf.reduce_join(a, [1, 0]) #==> ["abcd"]
tf.reduce_join(a, []) #==> ["abcd"]


<tf.Tensor 'ReduceJoin_9:0' shape=(2, 2) dtype=string>

### F) Other reduction opertions:

    1. tf.reduce_max
    2. tf.reduce_min
    3. tf.reduce_mean
    4. tf.reduce_logsumexp    